---
apiVersion: v1
kind: Pod
metadata:
  name: label-container
  labels:
    name: mainui
    rel: stable
spec:
  containers:
  - name: label-container
    image: nginx:1.14
    ports:
    - containerPort: 80
    