apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-pod
  labels:
    app: machinerunning
spec:
  containers:
  - image: tensorflow/tensorflow:nightly-jupyter
    name: tensorflow-pod
    ports:
    - containerPort: 8888
  nodeSelector:
    disktype: "ssd"
    gpu: "true"
    